# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Duplicacy
version: "0.0.7"
slug: duplicacy
description: Store securely encrypted backups on cloud storage services!
url: "https://github.com/nyok92/hassio-addons/tree/main/duplicacy"
image: "ghcr.io/nyok92/{arch}-duplicacy"
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
init: false
ports:
  3875/tcp: null
ports_description:
  3875/tcp: Web frontend (not needed with Ingress)
ingress: true
ingress_port: 3875
apparmor: true
panel_title: Duplicacy
panel_icon: mdi:backup-restore
map:
  - addon_config:rw
  - backup:rw
  - media:rw
  - share:rw
options:
  timezone: "Europe/Paris"
schema:
  timezone: "str?"
