# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Duplicacy
version: "1.8.3"
slug: duplicacy
description: Store securely encrypted backups on cloud storage services!
url: "https://github.com/nyok92/hassio-addons/tree/main/duplicacy"
image: "ghcr.io/nyok92/{arch}-duplicacy"
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
init: false
ports:
  3876/tcp: null
ports_description:
  3876/tcp: Web frontend (not needed with Ingress)
ingress: true
ingress_port: 3876
panel_title: Duplicacy
panel_icon: mdi:backup-restore
apparmor: false
map:
  - homeassistant_config:rw
  - addon_config:rw
#  - addons:rw
#  - backup:rw
  - share:rw
options:
  timezone: "Europe/Paris"
  version: "1.8.1"
  USR_ID: 0
  GRP_ID: 0
  domain: "localhost"
  mqtt: false
  mqtt_hostname: "core-mosquitto"
  mqtt_username: "mqttuser"
  mqtt_password: "mqttuserpwd"
  mqtt_port: 1883
  log_dir: "/config/mqtt/logs"
  configfile: "/config/mqtt/config.json"
  backup_dir: ""
  backup_name: ""
schema:
  timezone: "str"
  version: "str"
  USR_ID: "int"
  GRP_ID: "int"
  domain: "str"
  mqtt: bool
  mqtt_hostname: "str?"
  mqtt_username: "str?"
  mqtt_password: "str?"
  mqtt_port: "int?"
  log_dir: "str?"
  configfile: "str?"
  backup_dir: "str?"
  backup_name: "str?"
