# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Duplicacy
version: "0.0.8"
slug: duplicacy
description: Store securely encrypted backups on cloud storage services!
url: "https://github.com/nyok92/hassio-addons/tree/main/duplicacy"
image: "ghcr.io/nyok92/{arch}-duplicacy"
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
init: false
ports:
  3876/tcp: null
ports_description:
  3876/tcp: Web frontend (not needed with Ingress)
ingress: true
ingress_port: 3876
panel_title: Duplicacy
panel_icon: mdi:backup-restore
apparmor: false
map:
  - homeassistant_config:rw
  - addon_config:rw
#  - addons:rw
#  - backup:rw
  - share:rw
  - all_addon_configs:rw
options:
  timezone: "Europe/Paris"
  version: "latest"
  USR_ID: 0
  GRP_ID: 0
  domain: null
  mqtt: false
    mqtt_hostname: "127.0.0.1"
    mqtt_username: "mqttuser"
    mqtt_password: "mqttuserpwd"
    log_dir: "/path/to/logfolder"
schema:
  timezone: "str"
  version: "str"
  USR_ID: "int"
  GRP_ID: "int"
  domain: "str"
  mqtt: bool
    mqtt_hostname: "str?"
    mqtt_username: "str?"
    mqtt_password: "str?"
    log_dir: "str?"
