# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Duplicacy2
version: "0.0.7"
slug: duplicacy2
description: Store securely encrypted backups on cloud storage services!
url: "https://github.com/nyok92/hassio-addons/tree/main/duplicacy2"
image: "ghcr.io/nyok92/{arch}-duplicacy2"
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
init: false
ports:
  3875/tcp: null
ports_description:
  3875/tcp: Web frontend (not needed with Ingress)
ingress: true
ingress_port: 3875
panel_title: Duplicacy2
panel_icon: mdi:backup-restore
map:
  - homeassistant_config:rw
  - addon_config:rw
  - ssl:rw
  - addons:rw
  - backup:rw
  - share:rw
  - media:rw
  - all_addon_configs:rw
options:
  timezone: "Europe/Paris"
  version: "latest"
  USR_ID: 0
  GRP_ID: 0
schema:
  timezone: "str?"
  version: "str?"
  USR_ID: "int?"
  GRP_ID: "int?"
