# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Duplicacy2
version: "0.0.7"
slug: duplicacy2
description: Store securely encrypted backups on cloud storage services!
url: "https://github.com/nyok92/hassio-addons/tree/main/duplicacy2"
image: "ghcr.io/nyok92/{arch}-duplicacy2"
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
init: false
ports:
  3876/tcp: null
ports_description:
  3876/tcp: Web frontend (not needed with Ingress)
ingress: true
ingress_port: 3876
panel_title: Duplicacy2
panel_icon: mdi:backup-restore
apparmor: false
map:
  - homeassistant_config:rw
  - addon_config:rw
#  - addons:rw
#  - backup:rw
  - share:rw
  - all_addon_configs:rw
options:
  timezone: "Europe/Paris"
  version: "latest"
  USR_ID: 0
  GRP_ID: 0
  domain: null
  customize:
    active: false
    default: nginx_proxy_default*.conf
    servers: nginx_proxy/*.conf
schema:
  timezone: "str?"
  version: "str?"
  USR_ID: "int?"
  GRP_ID: "int?"
  domain: str
  customize:
    active: bool
    default: str
    servers: str
