# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:buster"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:buster"
#  armhf: "ghcr.io/home-assistant/armhf-base-debian:buster"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:buster"
  i386: "ghcr.io/home-assistant/i386-base-debian:buster"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Duplicati add-on"
  org.opencontainers.image.description: "Duplicati add-on Backup Software."
  org.opencontainers.image.source: "https://github.com/nyok92/hassio-addons/duplicati"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
  MONO_VERSION: "6.12.0.182"
