# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:latest"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:latest"
#  armhf: "ghcr.io/home-assistant/armhf-base-debian:latest"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:latest"
#  i386: "ghcr.io/home-assistant/i386-base-debian:latest"
labels:
  org.opencontainers.image.title: "Duplicati addon"
  org.opencontainers.image.description: "Duplicati add-on"
  org.opencontainers.image.source: "https://github.com/nyok92/hassio-addons/duplicati"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
  DUPLICATI_RELEASE: "v2.1.0.2_beta_2024-11-29"
