# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Duplicati
version: "2.0.8.1"
slug: duplicati
description: Store securely encrypted backups on cloud storage services!
url: "https://github.com/nyok92/hassio-addons/tree/main/duplicati"
image: "ghcr.io/nyok92/{arch}-duplicati"
arch:
  - armhf
  - armv7
  - amd64
  - i386
  - aarch64
init: false
ports:
  8200/tcp: null
ports_description:
  8200/tcp: Web frontend (not needed with Ingress)
ingress: true
ingress_port: 8200
panel_title: Duplicati
panel_icon: mdi:backup-restore
#privileged:
#- DAC_READ_SEARCH
map:
  - addon_config:rw
  - addons:rw
  - homeassistant_config:rw
  - backup:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  timezone: "Europe/Paris"
  CLI_ARGS: ""
  USR_ID: 0
  GRP_ID: 0
schema:
  timezone: "str?"
  CLI_ARGS: "str?"
  USR_ID: "int"
  GRP_ID: "int"
