# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Kopia
version: "0.0.2"
slug: kopia
description: Store securely encrypted backups on cloud storage services!
url: "https://github.com/nyok92/hassio-addons/tree/main/kopia"
image: "ghcr.io/nyok92/{arch}-kopia"
arch:
  - armhf
  - armv7
  - amd64
  - i386
  - aarch64
init: false
ports:
  51515/tcp: null
ports_description:
  51515/tcp: Web frontend (not needed with Ingress)
ingress: true
ingress_port: 51515
panel_title: kopia
panel_icon: mdi:backup-restore
devices:
- /dev/fuse
privileged:
- SYS_ADMIN
tmpfs: true
map:
#  - homeassistant_config:rw
  - addon_config:rw
#  - ssl:ro
#  - addons:rw
  - backup:rw
  - share:rw
  - media:rw
options:
  timezone: "Europe/Paris"
  ssl: false
  certfile: "/config/keys/kopia.crt"
  keyfile: "/config/keys/kopia.key"
  REFRESH_INTERVAL: "300s"
  KOPIA_UI_USERNAME: "kopia"
  KOPIA_UI_PASSWORD: "kopiapassword"
schema:
  timezone: "str?"
  ssl: "bool?"
  certfile: "str?"
  keyfile: "str?"
  REFRESH_INTERVAL: "str?"
  KOPIA_UI_USERNAME: "str"
  KOPIA_UI_PASSWORD: "str"
