# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Kopia add-on
version: "0.0.1"
slug: kopia
description: Store securely encrypted backups on cloud storage services!
url: "https://github.com/nyok92/hassio-addons/tree/main/kopia"
arch:
  - armhf
  - armv7
  - amd64
  - i386
  - aarch64
ingress: true
ingress_port: 51515
panel_icon: mdi:backup-restore
startup: services
init: false
backup_exclude: ["/backup"]

privileged:
- DAC_READ_SEARCH
map:
  - config:rw
  - ssl:rw
  - media:rw
  - addons:rw
  - share:rw
  - backup:rw
image: "ghcr.io/nyok92/{arch}-addon-duplicati"
