# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Kopia
version: "0.0.2"
slug: kopia
description: Store securely encrypted backups on cloud storage services!
url: "https://github.com/nyok92/hassio-addons/tree/main/kopia"
image: "ghcr.io/nyok92/{arch}-kopia"
arch:
  - armhf
  - armv7
  - amd64
  - i386
  - aarch64
init: false
#hassio_role: "backup"
#hassio_api: true
#homeassistant_api: true
ports:
  51515/tcp: null
ports_description:
  51515/tcp: Web frontend (not needed with Ingress)
ingress: true
ingress_port: 51515
panel_title: kopia
panel_icon: mdi:backup-restore
#startup: application
backup_exclude: ["/backup"]
privileged:
- DAC_READ_SEARCH
map:
  - addon_config:rw
  - addons:rw
  - homeassistant_config:rw
  - backup:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  KOPIA_HTTPS: "false"
  private_key_file: /ssl/rsync/id_rsa
  REFRESH_INTERVAL: "300s"
  KOPIA_UI_USERNAME: "kopia"
  KOPIA_UI_PASSWORD: "kopiapassword"
schema:
  KOPIA_HTTPS: "bool"
  private_key_file: match(^/ssl/.+)
  REFRESH_INTERVAL: "str?"
  KOPIA_UI_USERNAME: "str"
  KOPIA_UI_PASSWORD: "str"
